Repository DARIAH-ERIC/dariah-campus, pull requests merged in 2024-08, with the labels that each got.

#1163 content(cms): create Tag "corpus-analysis"
  content/tags/corpus-analysis.yml
Labels: decap-cms/draft

#1182 content(cms): create Person "börner-ingo"
  content/people/börner-ingo.yml
  content/people/images/ingo-boerner.jpg
Labels: decap-cms/pending_publish

#1184 content(cms): create Person "trilcke-peer"
  content/people/images/peer-trilcke.jpg
  content/people/trilcke-peer.yml
Labels: decap-cms/pending_publish

#1185 content(cms): create Person "wünsche-katharina-ruth"
  content/people/images/katharina-ruth-wuensche.png
  content/people/wünsche-katharina-ruth.yml
Labels: decap-cms/pending_publish

#1186 content(cms): create Person "plank-lukas"
  content/people/images/lukas-plank.png
  content/people/plank-lukas.yml
Labels: decap-cms/pending_publish

#1188 content(cms): create Person "charvat-vera"
  content/people/charvat-vera.yml
  content/people/images/vera-charvat.png
Labels: decap-cms/pending_publish

#1189 content(cms): update Resource "clarin-tools-and-resources-for-lexicographic-work/index"
  content/posts/clarin-tools-and-resources-for-lexicographic-work/index.mdx
Labels: decap-cms/pending_publish

#1190 content(cms): create Person "giovannini-luca"
  content/people/giovannini-luca.yml
  content/people/images/luca-giovannini.jpg
Labels: decap-cms/pending_publish

#1191 content(cms): create Person "resch-stefan"
  content/people/images/stefan-resch.png
  content/people/resch-stefan.yml
Labels: decap-cms/pending_publish

#1192 content(cms): create Person "schwindt-mark"
  content/people/images/mark-schwindt.jpeg
  content/people/schwindt-mark.yml
Labels: decap-cms/pending_publish

#1193 content(cms): create Person "skorinkin-daniil"
  content/people/images/daniil-skorinkin.jpeg
  content/people/skorinkin-daniil.yml
Labels: decap-cms/pending_publish

#1194 content(cms): create Person "sluyter-gaethje-henny"
  content/people/images/henny-sluyter-gaethje.jpg
  content/people/sluyter-gaethje-henny.yml
Labels: decap-cms/pending_publish

#1195 content(cms): update Person "schöch-christof"
  content/people/images/christof-schoech.jpeg
  content/people/schöch-christof.yml
Labels: decap-cms/pending_publish

#1196 content(cms): update Curriculum "the-parthenos-complete-guide-to-research-infrastructures/index"
  content/courses/the-parthenos-complete-guide-to-research-infrastructures/index.mdx
Labels: decap-cms/pending_publish

#1197 content(cms): update Event "open-data-citation-for-social-science-and-humanities/index"
  content/events/open-data-citation-for-social-science-and-humanities/index.mdx
Labels: decap-cms/pending_publish

#1199 content(cms): create Person "de-silva-felipe"
  content/people/de-silva-felipe.yml
Labels: decap-cms/pending_publish

#1200 content(cms): create Person "fernandes-joão"
  content/people/fernandes-joão.yml
Labels: decap-cms/pending_publish

#1201 content(cms): create Person "castaña-iñes"
  content/people/castaña-iñes.yml
Labels: decap-cms/pending_publish

#1198 content(cms): update Event "shaping-new-approaches-to-data-management-in-arts-and-humanities/index"
  content/events/shaping-new-approaches-to-data-management-in-arts-and-humanities/index.mdx
Labels: decap-cms/pending_publish

#1203 content(cms): create Person "herrmann-berenike"
  content/people/herrmann-berenike.yml
Labels: decap-cms/pending_publish

#1204 content(cms): create Person "hodel-tobias"
  content/people/hodel-tobias.yml
Labels: decap-cms/pending_publish

#1202 content(cms): update Event "sharing-the-experience-workflows-for-the-digital-humanities/index"
  content/events/sharing-the-experience-workflows-for-the-digital-humanities/index.mdx
Labels: decap-cms/pending_publish

#1209 content(cms): create Person "janco-andrew-1"
  content/people/janco-andrew-1.yml
Labels: netlify-cms/pending_publish

#1210 content(cms): create Person "budak-nick"
  content/people/budak-nick.yml
Labels: netlify-cms/pending_publish

#1211 content(cms): create Person "ermolaev-natalia"
  content/people/ermolaev-natalia.yml
Labels: netlify-cms/pending_publish

#1212 content(cms): create Curriculum "new-languages-for-nlp/index"
  content/courses/new-languages-for-nlp/index.mdx
Labels: netlify-cms/pending_publish

#1213 content(cms): create Resource "nlp-for-humanists-an-introduction-to-key-concepts-and-workflows/index"
  content/posts/nlp-for-humanists-an-introduction-to-key-concepts-and-workflows/index.mdx
Labels: decap-cms/pending_publish

#1214 content(cms): create Resource "practical-introduction-to-spacy-for-humanists/index"
  content/posts/practical-introduction-to-spacy-for-humanists/index.mdx
Labels: decap-cms/pending_publish

#1215 content(cms): update Curriculum "new-languages-for-nlp/index"
  content/courses/new-languages-for-nlp/index.mdx
Labels: decap-cms/pending_publish

#1218 content(cms): create Resource "machine-learning-for-nlp/index"
  content/posts/machine-learning-for-nlp/images/model-stages.png
  content/posts/machine-learning-for-nlp/index.mdx
Labels: decap-cms/pending_publish

#1219 content(cms): update Curriculum "new-languages-for-nlp/index"
  content/courses/new-languages-for-nlp/index.mdx
Labels: decap-cms/pending_publish

#1221 content(cms): update Curriculum "new-languages-for-nlp/index"
  content/courses/new-languages-for-nlp/index.mdx
Labels: decap-cms/pending_publish

#1222 content(cms): create Resource "cadet-preparing-data-for-new-language-models-in-spacy/index"
  content/posts/cadet-preparing-data-for-new-language-models-in-spacy/index.mdx
Labels: decap-cms/pending_publish

#1223 content(cms): create Resource "annotating-linguistic-data-with-inception/index"
  content/posts/annotating-linguistic-data-with-inception/index.mdx
Labels: decap-cms/pending_publish

#1224 content(cms): create Resource "training-new-language-models-in-spacy/index"
  content/posts/training-new-language-models-in-spacy/index.mdx
Labels: decap-cms/pending_publish

#1225 content(cms): create Resource "applying-new-language-model-in-spacy/index"
  content/posts/applying-new-language-model-in-spacy/index.mdx
Labels: decap-cms/pending_publish

#1226 content(cms): create Resource "a-pathfinder-to-nlp-resources-for-humanists/index"
  content/posts/a-pathfinder-to-nlp-resources-for-humanists/index.mdx
Labels: decap-cms/pending_publish

#1227 content(cms): update Curriculum "new-languages-for-nlp/index"
  content/courses/new-languages-for-nlp/index.mdx
Labels: decap-cms/pending_publish

#1229 content(cms): update Person "ermolaev-natalia"
  content/people/ermolaev-natalia.yml
  content/people/images/natashaermolaev.5135a36b.fill-1250x938.jpeg
Labels: decap-cms/pending_publish

#1230 content(cms): update Resource "nlp-for-humanists-an-introduction-to-key-concepts-and-workflows/index"
  content/posts/nlp-for-humanists-an-introduction-to-key-concepts-and-workflows/index.mdx
Labels: decap-cms/pending_publish
